package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/Maxi-Mega/s3-image-server-v2/internal/types"
	"github.com/Maxi-Mega/s3-image-server-v2/internal/web/graph/model"
)

// FileSelectors is the resolver for the fileSelectors field.
func (r *dynamicDataResolver) FileSelectors(ctx context.Context, obj *model.DynamicData) (map[string]any, error) {
	return toMapStringAny(obj.FileSelectors), nil
}

// Expressions is the resolver for the expressions field.
func (r *dynamicDataResolver) Expressions(ctx context.Context, obj *model.DynamicData) (map[string]any, error) {
	return toMapStringAny(obj.Expressions), nil
}

// CachedFileLinks is the resolver for the cachedFileLinks field.
func (r *imageResolver) CachedFileLinks(ctx context.Context, obj *types.Image) (map[string]any, error) {
	return toMapStringAny(obj.CachedFileLinks), nil
}

// SignedURLs is the resolver for the signedURLs field.
func (r *imageResolver) SignedURLs(ctx context.Context, obj *types.Image) (map[string]any, error) {
	return toMapStringAny(obj.SignedURLs), nil
}

// DynamicFilters is the resolver for the dynamicFilters field.
func (r *imageSummaryResolver) DynamicFilters(ctx context.Context, obj *types.ImageSummary) (map[string]any, error) {
	return toMapStringAny(obj.DynamicFilters), nil
}

// GetAllImageSummaries is the resolver for the getAllImageSummaries field.
func (r *queryResolver) GetAllImageSummaries(ctx context.Context, from *time.Time, to *time.Time) (types.AllImageSummaries, error) {
	start := time.Date(0, 1, 1, 0, 0, 0, 0, time.UTC)
	end := time.Now().Add(24 * time.Hour)

	if from != nil {
		start = *from
	}

	if to != nil {
		end = *to
	}

	if start.After(end) {
		return nil, errInvalidTimeRange
	}

	return r.Cache.GetAllImages(ctx, start, end), nil
}

// GetImage is the resolver for the getImage field.
func (r *queryResolver) GetImage(ctx context.Context, bucket string, name string) (*types.Image, error) {
	img, err := r.Cache.GetImage(ctx, bucket, name)
	if err != nil {
		if errors.Is(err, types.ErrImageNotFound) {
			return nil, nil
		}

		return nil, err
	}

	return &img, nil
}

// GetDynamicData is the resolver for the getDynamicData field.
func (r *queryResolver) GetDynamicData(ctx context.Context, group string, typeArg string) (*model.DynamicData, error) {
	for _, grp := range r.Config.Products.ImageGroups {
		if grp.GroupName == group {
			for _, typ := range grp.Types {
				if typ.Name == typeArg {
					return convertDynamicData(typ.DynamicData)
				}
			}

			return nil, fmt.Errorf("image type %q %w in group %q", typeArg, errNotFound, group)
		}
	}

	return nil, fmt.Errorf("image group %q %w", group, errNotFound)
}

// DynamicData returns DynamicDataResolver implementation.
func (r *Resolver) DynamicData() DynamicDataResolver { return &dynamicDataResolver{r} }

// Image returns ImageResolver implementation.
func (r *Resolver) Image() ImageResolver { return &imageResolver{r} }

// ImageSummary returns ImageSummaryResolver implementation.
func (r *Resolver) ImageSummary() ImageSummaryResolver { return &imageSummaryResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type dynamicDataResolver struct{ *Resolver }
type imageResolver struct{ *Resolver }
type imageSummaryResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
